version: '3.9'
services:
  mysql-contenedor:
    image: mysql:5.7
    container_name: mysql-contenedor
    restart: always
    environment:
      MYSQL_DATABASE: 'srs-dev'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'